### ISSUE TITLE
Concurrent events problem

### ISSUE THREAD

**Issue by breathbath** [Metabor/Statemachine#17]
In the implementation of the statemachine we came  across a problem that we receive a chain of unordered events or even some events earlier than others.
Imagine we have the following SM setup (start state stateA):
stateA->stateB triggered by Event 1
stateB->stateC triggered by Event 2
Imagine we receive Event 2 and after some time Event 1. We consider it to be a normal situation and want the order to be in stateC afterwards. How would you solve this? 
We can queue all the incoming events but we don't know in which order it is expected to process them (as this logic is hidden in the statemachine). Probably we should be able to receive the state/event sequences and then sort your incoming events by this list? Or we should limit our externals in possibility to send unsorted events and make them call us in an expected order. 

Another case when the events appear simultaneously:
stateA->stateB triggered by event1
stateA->stateC triggered by event2
imagine we started processing transition stateA-stateB, but we didn't store the current state yet as we need time to process logic related to this transition. At the same time we process also transition stateA->stateC and then we see in the history that order goes first to stateB and then to stateC and at the end it's not predictable in which state orders will be which is of course not desirable. How would you solve this? Also consider the situation when the first transition is not made but the second can be made, so we don't want to loose the event2 execution (if we for example lock the order for the first transition). 

Thanks in advance

**Comment by Metabor** [comment]
Normally best is to get events in the right order, but real world is often not sequentially but super parallel.
If the use case of your Statemachine is not to prevent your stateful subject from wrong events, you can collect or queue the events, like you described, to bring them in right order. In this case use the hasEvent() method of currentState to check if you can now process this event.
Downside of this solution is, that wrong signals from outside, that also could be a signal for an error that happend, will be silently ignored.
I don't know your usecase, so you have to check if this could be a problem for you.

The other thing (missing lock) is something that I had on my TODO-List for a long time (MetaborStd has the related interfaces since over a year:
https://github.com/Metabor/MetaborStd/commit/a9c41d43e3ad5f198e6392e995ab0bdaf1d51a2a

So I put this as a milestone for the next release (the last one was released today).
If you want, you can join the branch:
https://github.com/Metabor/Statemachine/tree/add_lock_to_statemachine

Will also integrate a library for different locks or better make a bridge for that.
This library looks good to me for this solution:
https://github.com/arvenil/ninja-mutex

What did you think?

**Comment by Metabor** [comment]
I am not sure if my answer has helped you. If yes, you can close this issue, otherwise write here if something is still unclear.
You are also welcome to join on:
https://github.com/Metabor/Statemachine/tree/add_lock_to_statemachine
;)

**Comment by breathbath** [comment]
Sorry I was on vacation and just saw your answer. Let me check everything and I'll answer after couple of days!

**Comment by breathbath** [comment]
I've added some comments to the pull request. As for ninja it is just a bunch of different wrappers around the single locking interface. It's useful in a concrete application rather than in the package as it contains too many implementation details. We could easily reuse/copy couple of abstractions from there but not more.

**Comment by breathbath** [comment]
As for order of events you're suggesting to check for every queued event if the current state has it. It would be of course nice to decide on the application level the strategy of resolving not sorted events. But you think it's not the part of the package logic?

**Comment by breathbath** [comment]
Method isLocked is never used!

**Comment by Metabor** [comment]
Mechanism for locking is now implemented in the library.
You need either set a mutex factory on the statemachine factory (setMutexFactory):
https://github.com/Metabor/Statemachine/blob/master/src/Metabor/Statemachine/Factory/Factory.php#L56
Or add a mutex instance when creating a statemachine instance as a constructor parameter:
https://github.com/Metabor/Statemachine/blob/master/src/Metabor/Statemachine/Statemachine.php#L90
What you use depends on the way you create your statemachine in your project (but I recommend the factory way).
